### ISSUE TITLE
Multi Core support?

### ISSUE THREAD

**Issue by jaequery** [Austin-Williams/zcash-guides#5]
Hi there, does this script utilize multi-core? If so, is there a place where we can set how many CPUs to utilize? Thanks!

**Comment by hazinstore** [comment]
Yes and my testing shows that on the higher iops limit instances in aws you can get a significant boost by setting genproclimit based on RAM instead of cores.  Seems like the optimum is 1GB per thread, not per core, this is because the AWS instances are bursty.  So if you have the r3.xlarge with 4 cores and 30.5 GB of ram you can set genproclimit to 30 so each thread gets 1GB of RAM and it works extraordinarily well. Especially for spot instances you are WAY better off with the r3 instances than the others.

Why does this work?  It's because you aren't actually buying cores on AWS you are buying "core credits", and you can burn these as fast as you want.  The underlaying hardware will pick up the threads and run them as quickly as it can.  All the "core count" means is the minimum number of threads you are guaranteed to have execute a certain number of ops in a given timeframe.  The rest is illusory stuff they are feeding the OS so it can schedule things better.  Remember you don't have hard CPUs in AWS they are all software CPUs.

Also using the ubuntu to build is a bad idea, you'll have issues with system d killing your processes off once you leave them idle long enough.

You're better off using the amazon HVM OS, but building zcashd locally as a statically compiled binary, then stripping the binary.  Fully stripped it should have a size of around 35MB.
