### ISSUE TITLE
 Mining Viability?

### ISSUE THREAD

**Issue by ronakjain90** [Austin-Williams/zcash-guides#8]
Hi Austin,

Really thanks for the tutorial. I've been able to setup mining operations in Amazon ec2 cloud. I'm using M4.large machine for my mining operations.

see the below information

```
ubuntu@ip-172-31-2-110:~$ ~/zcash/./src/zcash-cli getinfo
{
    "version" : 1000050,
    "protocolversion" : 170002,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 1902,
    "timeoffset" : 0,
    "connections" : 8,
    "proxy" : "",
    "difficulty" : 66142.56366860,
    "testnet" : false,
    "keypoololdest" : 1477827517,
    "keypoolsize" : 29999,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00005000,
    "errors" : ""
}
```
Despite mining on a fairly powerful machine for more than 20 hours, my balance is still 0. Is it a viable option to mine in your opinion? Or do we need powerful hashing machine, just like bitcoin. I'm using EC2 Spot instance for around $0.017/hr. Let me know your opinion.

**Comment by Austin-Williams** [comment]
I don't think mining in EC2 is viable presently. The difficulty is very
high. You may be better off mining to a pool (at least then you'll get
periodic payouts) rather than solo mining on EC2.

I don't have a guide for pool mining yet, but I have been able to mine to
flypool.

However, I've found even pool mining to be not worth it at the present
difficulty level / payout / price.

When I get some more time next week I may try GPU mining on EC2 and see if
there is any profit to be had.
